services:
  api:
   build:
     context: .
     dockerfile: Todolist.Api/Dockerfile
   ports:
     - "5000:80" 
   depends_on:
    - db
   environment:
   - ConnectionStrings__DefaultConnection=Server=db;Database=TaskItemDb;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
   - ASPNETCORE_ENVIRONMENT=Development
   networks:
   - todolist_network 

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: todolist_sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - todolist_network 

    
networks:
  todolist_network:
    driver: bridge